attack_label_trans: all2one
attack_target: 1
pratio: 0.1
attack: blended
#attack_trigger_img_path: ../resource/blended/hello_kitty.jpeg
attack_trigger_img_path: ../resource/blended/random_image.png
attack_train_blended_alpha: 0.2
attack_test_blended_alpha: 0.5